### PR TITLE
Change ColorColumn to match CursorColumn

### PR DESCRIPTION
**Pull request by joshgillies**

### CODE REVIEW

**Comment by robertmeta** [comment]
Why would you want ColorColumn to look like CursorColumn?

**Comment by joshgillies** [comment]
Sorry, I should have left more of a description.

Personally I have: `let &colorcolumn=join(range(81,999),",")`, and with the `nofrils-dark` default ColorColumn I find theres too much contrast. I'll attach a screenshot to illustrate the difference.

screen shot 2016-03-22 at 11 21 21 am

**Comment by robertmeta** [comment]
Thank you so much for the clarification!  Unfortunately, I suspect this is a fairly rare configuration and fixing it for your case would make it worse for the more common case.  I might add an optional behavior like strbackgrounds.

Wouldn't you want it to be different from cursorcolumn (else cursorcolumn would vanish on the right side)?

**Comment by joshgillies** [comment]
Oh I'm sure there's a better way of managing this, and my usage of ColorColumn is very likely an edge-case. But having an optional setting could be a good way around this.

> Wouldn't you want it to be different from cursorcolumn (else cursorcolumn would vanish on the right side)?

Interestingly enough, even with the default settings CursorCulumn falls behind ColorColumn (see screenshot in my last post).

**Comment by robertmeta** [comment]
CursorLine is blown out by ColorColumn, ColorColumn is interestingly not.  But, I think just having a less aggressive set of colors will handle this best for all cases.

**Comment by robertmeta** [comment]
I committed much milder color shifts for ColorColumn that work with CursorLine and CursorColumn -- hopefully that will work for you and others.

**Comment by joshgillies** [comment]
Latest commit is :ok_hand: thanks for pushing this out, and for your work on nofrils! Really loving this minimal colour scheme.  :clap:

**Pull request closed without merging**
